package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallBankCard;
import org.linlinjava.litemall.db.domain.LitemallBankCardExample;

public interface LitemallBankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int countByExample(LitemallBankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallBankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int insert(LitemallBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int insertSelective(LitemallBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    List<LitemallBankCard> selectByExample(LitemallBankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    LitemallBankCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallBankCard record, @Param("example") LitemallBankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallBankCard record, @Param("example") LitemallBankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LitemallBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bank_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LitemallBankCard record);
}