package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMainCabinet;
import org.linlinjava.litemall.db.domain.LitemallMainCabinetExample;

public interface LitemallMainCabinetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int countByExample(LitemallMainCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallMainCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int insert(LitemallMainCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int insertSelective(LitemallMainCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    List<LitemallMainCabinet> selectByExample(LitemallMainCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    LitemallMainCabinet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallMainCabinet record, @Param("example") LitemallMainCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallMainCabinet record, @Param("example") LitemallMainCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LitemallMainCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_main_cabinet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LitemallMainCabinet record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 查询柜组信息
     * @param mainCabinet
     * @return
     */
    List<LitemallMainCabinet> listAllNum(LitemallMainCabinet mainCabinet);
}