package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMainCabinet;
import org.linlinjava.litemall.db.domain.LitemallMainCabinetExample;
import org.linlinjava.litemall.db.domain.LitemallSubCabinet;
import org.linlinjava.litemall.db.domain.LitemallSubCabinetExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface LitemallSubCabinetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int countByExample(LitemallSubCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallSubCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int insert(LitemallSubCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int insertSelective(LitemallSubCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    List<LitemallSubCabinet> selectByExample(LitemallSubCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    LitemallSubCabinet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallSubCabinet record, @Param("example") LitemallSubCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallSubCabinet record, @Param("example") LitemallSubCabinetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LitemallSubCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sub_cabinet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LitemallSubCabinet record);

    /**
     * 逻辑删除(修改删除标识)
     * @param id
     * @return
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 查询主柜编号
     *
     */
    List<LitemallMainCabinet> listMainNum(LitemallMainCabinetExample example);

    /**
     * 查询柜组编码和柜子信息
     * @param map
     * @return
     */
    List<LitemallSubCabinet> listByExample(@SuppressWarnings("rawtypes") Map map);
    
    /**
     * 将一分钟前时间并状态为取包中的子柜修改成空闲状态
     * @param date
     * @return
     */
    int upStatusByUpdateTime(Date date);


}