package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStandards;
import org.linlinjava.litemall.db.domain.LitemallStandardsAndCount;
import org.linlinjava.litemall.db.domain.LitemallStandardsExample;

import java.util.List;
import java.util.Map;

public interface LitemallStandardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int countByExample(LitemallStandardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallStandardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int insert(LitemallStandards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int insertSelective(LitemallStandards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    List<LitemallStandards> selectByExample(LitemallStandardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallStandards record, @Param("example") LitemallStandardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_standards
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallStandards record, @Param("example") LitemallStandardsExample example);

    /**
     * 根据Id修改
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(LitemallStandards record);

    /**
     * 逻辑删除
     * @param id
     * @return
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 单个查询规格By Id
     */
    LitemallStandards queryStandards(Integer id);

    /**
     * 单个查询规格 By 子柜Id
     */
    LitemallStandards selectStanBySub(Integer subCabId);
    
  
    List<LitemallStandardsAndCount> getStandardList(Integer mainid);

    /**
     * 查询规格信息 + 柜组编码
     * @param map
     * @return
     */
    List<LitemallStandards> queryStand(@SuppressWarnings("rawtypes") Map map);
    
    /**
     * 谭糠
     * 根据柜组ID查询下面正常规则
     * @param mainId
     * @return
     */
    List<LitemallStandards> getSatnByMain(Integer mainId);
    
    /**
     * 单个查询
     * @param id
     * @return
     */
    LitemallStandards selectById(Integer id);

}