package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDeposit;
import org.linlinjava.litemall.db.domain.LitemallDepositExample;

import java.util.List;

public interface LitemallDepositMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int countByExample(LitemallDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int deleteByExample(LitemallDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int insert(LitemallDeposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int insertSelective(LitemallDeposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    List<LitemallDeposit> selectByExample(LitemallDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LitemallDeposit record, @Param("example") LitemallDepositExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LitemallDeposit record, @Param("example") LitemallDepositExample example);

    /**
     * 修改押金信息
     * @param deposit
     * @return
     */
    int updateByPrimaryKeySelective(LitemallDeposit deposit);

    /**
     * 谭糠
     * 根据订单ID查询
     * @param usaId
     * @return
     */
    LitemallDeposit getDspositByUsaId(Integer usaId);

    /**
     * 条件查询
     * @param deposit
     * @return
     */
    List<LitemallDeposit> selectDeposit(LitemallDeposit deposit);

    int queryCount(Integer depositUserId);
}