package org.linlinjava.litemall.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class LitemallCapitalRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_id
     *
     * @mbggenerated
     */
    private Integer capId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_userid
     *
     * @mbggenerated
     */
    private Integer capUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_money
     *
     * @mbggenerated
     */
    private String capMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_deal
     *
     * @mbggenerated
     */
    private String capDeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_dealid
     *
     * @mbggenerated
     */
    private Integer capDealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_datetime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+8")
    private Date capDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_title
     *
     * @mbggenerated
     */
    private String capTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_capital _record.cap_status
     *
     * @mbggenerated
     */
    private Integer capStatus;

    /**
     * 类型(1:押金;2:退款;3:支付)
     */
    private Integer capType;

    public Integer getCapType() {
        return capType;
    }

    public void setCapType(Integer capType) {
        this.capType = capType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_id
     *
     * @return the value of litemall_capital _record.cap_id
     *
     * @mbggenerated
     */
    public Integer getCapId() {
        return capId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_id
     *
     * @param capId the value for litemall_capital _record.cap_id
     *
     * @mbggenerated
     */
    public void setCapId(Integer capId) {
        this.capId = capId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_userid
     *
     * @return the value of litemall_capital _record.cap_userid
     *
     * @mbggenerated
     */
    public Integer getCapUserid() {
        return capUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_userid
     *
     * @param capUserid the value for litemall_capital _record.cap_userid
     *
     * @mbggenerated
     */
    public void setCapUserid(Integer capUserid) {
        this.capUserid = capUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_money
     *
     * @return the value of litemall_capital _record.cap_money
     *
     * @mbggenerated
     */
    public String getCapMoney() {
        return capMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_money
     *
     * @param capMoney the value for litemall_capital _record.cap_money
     *
     * @mbggenerated
     */
    public void setCapMoney(String capMoney) {
        this.capMoney = capMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_deal
     *
     * @return the value of litemall_capital _record.cap_deal
     *
     * @mbggenerated
     */
    public String getCapDeal() {
        return capDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_deal
     *
     * @param capDeal the value for litemall_capital _record.cap_deal
     *
     * @mbggenerated
     */
    public void setCapDeal(String capDeal) {
        this.capDeal = capDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_dealid
     *
     * @return the value of litemall_capital _record.cap_dealid
     *
     * @mbggenerated
     */
    public Integer getCapDealid() {
        return capDealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_dealid
     *
     * @param capDealid the value for litemall_capital _record.cap_dealid
     *
     * @mbggenerated
     */
    public void setCapDealid(Integer capDealid) {
        this.capDealid = capDealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_datetime
     *
     * @return the value of litemall_capital _record.cap_datetime
     *
     * @mbggenerated
     */
    public Date getCapDatetime() {
        return capDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_datetime
     *
     * @param capDatetime the value for litemall_capital _record.cap_datetime
     *
     * @mbggenerated
     */
    public void setCapDatetime(Date capDatetime) {
        this.capDatetime = capDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_title
     *
     * @return the value of litemall_capital _record.cap_title
     *
     * @mbggenerated
     */
    public String getCapTitle() {
        return capTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_title
     *
     * @param capTitle the value for litemall_capital _record.cap_title
     *
     * @mbggenerated
     */
    public void setCapTitle(String capTitle) {
        this.capTitle = capTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_capital _record.cap_status
     *
     * @return the value of litemall_capital _record.cap_status
     *
     * @mbggenerated
     */
    public Integer getCapStatus() {
        return capStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_capital _record.cap_status
     *
     * @param capStatus the value for litemall_capital _record.cap_status
     *
     * @mbggenerated
     */
    public void setCapStatus(Integer capStatus) {
        this.capStatus = capStatus;
    }
}