package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LitemallDepositExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public LitemallDepositExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepoIdIsNull() {
            addCriterion("depo_id is null");
            return (Criteria) this;
        }

        public Criteria andDepoIdIsNotNull() {
            addCriterion("depo_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepoIdEqualTo(Integer value) {
            addCriterion("depo_id =", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdNotEqualTo(Integer value) {
            addCriterion("depo_id <>", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdGreaterThan(Integer value) {
            addCriterion("depo_id >", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_id >=", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdLessThan(Integer value) {
            addCriterion("depo_id <", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdLessThanOrEqualTo(Integer value) {
            addCriterion("depo_id <=", value, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdIn(List<Integer> values) {
            addCriterion("depo_id in", values, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdNotIn(List<Integer> values) {
            addCriterion("depo_id not in", values, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdBetween(Integer value1, Integer value2) {
            addCriterion("depo_id between", value1, value2, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_id not between", value1, value2, "depoId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdIsNull() {
            addCriterion("depo_user_id is null");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdIsNotNull() {
            addCriterion("depo_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdEqualTo(Integer value) {
            addCriterion("depo_user_id =", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdNotEqualTo(Integer value) {
            addCriterion("depo_user_id <>", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdGreaterThan(Integer value) {
            addCriterion("depo_user_id >", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_user_id >=", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdLessThan(Integer value) {
            addCriterion("depo_user_id <", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("depo_user_id <=", value, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdIn(List<Integer> values) {
            addCriterion("depo_user_id in", values, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdNotIn(List<Integer> values) {
            addCriterion("depo_user_id not in", values, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdBetween(Integer value1, Integer value2) {
            addCriterion("depo_user_id between", value1, value2, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_user_id not between", value1, value2, "depoUserId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdIsNull() {
            addCriterion("depo_sub_id is null");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdIsNotNull() {
            addCriterion("depo_sub_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdEqualTo(Integer value) {
            addCriterion("depo_sub_id =", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdNotEqualTo(Integer value) {
            addCriterion("depo_sub_id <>", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdGreaterThan(Integer value) {
            addCriterion("depo_sub_id >", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_sub_id >=", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdLessThan(Integer value) {
            addCriterion("depo_sub_id <", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdLessThanOrEqualTo(Integer value) {
            addCriterion("depo_sub_id <=", value, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdIn(List<Integer> values) {
            addCriterion("depo_sub_id in", values, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdNotIn(List<Integer> values) {
            addCriterion("depo_sub_id not in", values, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdBetween(Integer value1, Integer value2) {
            addCriterion("depo_sub_id between", value1, value2, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoSubIdNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_sub_id not between", value1, value2, "depoSubId");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyIsNull() {
            addCriterion("depo_money is null");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyIsNotNull() {
            addCriterion("depo_money is not null");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyEqualTo(Integer value) {
            addCriterion("depo_money =", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyNotEqualTo(Integer value) {
            addCriterion("depo_money <>", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyGreaterThan(Integer value) {
            addCriterion("depo_money >", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_money >=", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyLessThan(Integer value) {
            addCriterion("depo_money <", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("depo_money <=", value, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyIn(List<Integer> values) {
            addCriterion("depo_money in", values, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyNotIn(List<Integer> values) {
            addCriterion("depo_money not in", values, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyBetween(Integer value1, Integer value2) {
            addCriterion("depo_money between", value1, value2, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_money not between", value1, value2, "depoMoney");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdIsNull() {
            addCriterion("depo_record_id is null");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdIsNotNull() {
            addCriterion("depo_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdEqualTo(Integer value) {
            addCriterion("depo_record_id =", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdNotEqualTo(Integer value) {
            addCriterion("depo_record_id <>", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdGreaterThan(Integer value) {
            addCriterion("depo_record_id >", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_record_id >=", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdLessThan(Integer value) {
            addCriterion("depo_record_id <", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("depo_record_id <=", value, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdIn(List<Integer> values) {
            addCriterion("depo_record_id in", values, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdNotIn(List<Integer> values) {
            addCriterion("depo_record_id not in", values, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("depo_record_id between", value1, value2, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_record_id not between", value1, value2, "depoRecordId");
            return (Criteria) this;
        }

        public Criteria andDepoStatusIsNull() {
            addCriterion("depo_status is null");
            return (Criteria) this;
        }

        public Criteria andDepoStatusIsNotNull() {
            addCriterion("depo_status is not null");
            return (Criteria) this;
        }

        public Criteria andDepoStatusEqualTo(Integer value) {
            addCriterion("depo_status =", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusNotEqualTo(Integer value) {
            addCriterion("depo_status <>", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusGreaterThan(Integer value) {
            addCriterion("depo_status >", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("depo_status >=", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusLessThan(Integer value) {
            addCriterion("depo_status <", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusLessThanOrEqualTo(Integer value) {
            addCriterion("depo_status <=", value, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusIn(List<Integer> values) {
            addCriterion("depo_status in", values, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusNotIn(List<Integer> values) {
            addCriterion("depo_status not in", values, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusBetween(Integer value1, Integer value2) {
            addCriterion("depo_status between", value1, value2, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andDepoStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("depo_status not between", value1, value2, "depoStatus");
            return (Criteria) this;
        }

        public Criteria andReturnTimeIsNull() {
            addCriterion("return_time is null");
            return (Criteria) this;
        }

        public Criteria andReturnTimeIsNotNull() {
            addCriterion("return_time is not null");
            return (Criteria) this;
        }

        public Criteria andReturnTimeEqualTo(Date value) {
            addCriterion("return_time =", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeNotEqualTo(Date value) {
            addCriterion("return_time <>", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeGreaterThan(Date value) {
            addCriterion("return_time >", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("return_time >=", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeLessThan(Date value) {
            addCriterion("return_time <", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeLessThanOrEqualTo(Date value) {
            addCriterion("return_time <=", value, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeIn(List<Date> values) {
            addCriterion("return_time in", values, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeNotIn(List<Date> values) {
            addCriterion("return_time not in", values, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeBetween(Date value1, Date value2) {
            addCriterion("return_time between", value1, value2, "returnTime");
            return (Criteria) this;
        }

        public Criteria andReturnTimeNotBetween(Date value1, Date value2) {
            addCriterion("return_time not between", value1, value2, "returnTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedIsNull() {
            addCriterion("depo_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedIsNotNull() {
            addCriterion("depo_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedEqualTo(Boolean value) {
            addCriterion("depo_deleted =", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedNotEqualTo(Boolean value) {
            addCriterion("depo_deleted <>", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedGreaterThan(Boolean value) {
            addCriterion("depo_deleted >", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("depo_deleted >=", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedLessThan(Boolean value) {
            addCriterion("depo_deleted <", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("depo_deleted <=", value, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedIn(List<Boolean> values) {
            addCriterion("depo_deleted in", values, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedNotIn(List<Boolean> values) {
            addCriterion("depo_deleted not in", values, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("depo_deleted between", value1, value2, "depoDeleted");
            return (Criteria) this;
        }

        public Criteria andDepoDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("depo_deleted not between", value1, value2, "depoDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_deposit
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_deposit
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}