package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class LitemallBankCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.card_num
     *
     * @mbggenerated
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.own_bank
     *
     * @mbggenerated
     */
    private String ownBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bank_card.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.id
     *
     * @return the value of litemall_bank_card.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.id
     *
     * @param id the value for litemall_bank_card.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.user_id
     *
     * @return the value of litemall_bank_card.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.user_id
     *
     * @param userId the value for litemall_bank_card.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.user_name
     *
     * @return the value of litemall_bank_card.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.user_name
     *
     * @param userName the value for litemall_bank_card.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.user_phone
     *
     * @return the value of litemall_bank_card.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.user_phone
     *
     * @param userPhone the value for litemall_bank_card.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.card_num
     *
     * @return the value of litemall_bank_card.card_num
     *
     * @mbggenerated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.card_num
     *
     * @param cardNum the value for litemall_bank_card.card_num
     *
     * @mbggenerated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.own_bank
     *
     * @return the value of litemall_bank_card.own_bank
     *
     * @mbggenerated
     */
    public String getOwnBank() {
        return ownBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.own_bank
     *
     * @param ownBank the value for litemall_bank_card.own_bank
     *
     * @mbggenerated
     */
    public void setOwnBank(String ownBank) {
        this.ownBank = ownBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.status
     *
     * @return the value of litemall_bank_card.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.status
     *
     * @param status the value for litemall_bank_card.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.add_time
     *
     * @return the value of litemall_bank_card.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.add_time
     *
     * @param addTime the value for litemall_bank_card.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.update_time
     *
     * @return the value of litemall_bank_card.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.update_time
     *
     * @param updateTime the value for litemall_bank_card.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bank_card.deleted
     *
     * @return the value of litemall_bank_card.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bank_card.deleted
     *
     * @param deleted the value for litemall_bank_card.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}