package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class LitemallMainCabinet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.main_cab_num
     *
     * @mbggenerated
     */
    private String mainCabNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.standard
     *
     * @mbggenerated
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.region
     *
     * @mbggenerated
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_main_cabinet.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.id
     *
     * @return the value of litemall_main_cabinet.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.id
     *
     * @param id the value for litemall_main_cabinet.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.main_cab_num
     *
     * @return the value of litemall_main_cabinet.main_cab_num
     *
     * @mbggenerated
     */
    public String getMainCabNum() {
        return mainCabNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.main_cab_num
     *
     * @param mainCabNum the value for litemall_main_cabinet.main_cab_num
     *
     * @mbggenerated
     */
    public void setMainCabNum(String mainCabNum) {
        this.mainCabNum = mainCabNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.status
     *
     * @return the value of litemall_main_cabinet.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.status
     *
     * @param status the value for litemall_main_cabinet.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.standard
     *
     * @return the value of litemall_main_cabinet.standard
     *
     * @mbggenerated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.standard
     *
     * @param standard the value for litemall_main_cabinet.standard
     *
     * @mbggenerated
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.region
     *
     * @return the value of litemall_main_cabinet.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.region
     *
     * @param region the value for litemall_main_cabinet.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.add_time
     *
     * @return the value of litemall_main_cabinet.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.add_time
     *
     * @param addTime the value for litemall_main_cabinet.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.update_time
     *
     * @return the value of litemall_main_cabinet.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.update_time
     *
     * @param updateTime the value for litemall_main_cabinet.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_main_cabinet.deleted
     *
     * @return the value of litemall_main_cabinet.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_main_cabinet.deleted
     *
     * @param deleted the value for litemall_main_cabinet.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}