package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class LitemallCashord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.bank_id
     *
     * @mbggenerated
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.admin_user_id
     *
     * @mbggenerated
     */
    private Integer adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.sub_time
     *
     * @mbggenerated
     */
    private Date subTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.up_time
     *
     * @mbggenerated
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cashord.delete
     *
     * @mbggenerated
     */
    private Boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.id
     *
     * @return the value of litemall_cashord.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.id
     *
     * @param id the value for litemall_cashord.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.money
     *
     * @return the value of litemall_cashord.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.money
     *
     * @param money the value for litemall_cashord.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.user_id
     *
     * @return the value of litemall_cashord.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.user_id
     *
     * @param userId the value for litemall_cashord.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.bank_id
     *
     * @return the value of litemall_cashord.bank_id
     *
     * @mbggenerated
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.bank_id
     *
     * @param bankId the value for litemall_cashord.bank_id
     *
     * @mbggenerated
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.admin_user_id
     *
     * @return the value of litemall_cashord.admin_user_id
     *
     * @mbggenerated
     */
    public Integer getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.admin_user_id
     *
     * @param adminUserId the value for litemall_cashord.admin_user_id
     *
     * @mbggenerated
     */
    public void setAdminUserId(Integer adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.status
     *
     * @return the value of litemall_cashord.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.status
     *
     * @param status the value for litemall_cashord.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.sub_time
     *
     * @return the value of litemall_cashord.sub_time
     *
     * @mbggenerated
     */
    public Date getSubTime() {
        return subTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.sub_time
     *
     * @param subTime the value for litemall_cashord.sub_time
     *
     * @mbggenerated
     */
    public void setSubTime(Date subTime) {
        this.subTime = subTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.remarks
     *
     * @return the value of litemall_cashord.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.remarks
     *
     * @param remarks the value for litemall_cashord.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.up_time
     *
     * @return the value of litemall_cashord.up_time
     *
     * @mbggenerated
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.up_time
     *
     * @param upTime the value for litemall_cashord.up_time
     *
     * @mbggenerated
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cashord.delete
     *
     * @return the value of litemall_cashord.delete
     *
     * @mbggenerated
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cashord.delete
     *
     * @param delete the value for litemall_cashord.delete
     *
     * @mbggenerated
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }
}