spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8
  redis:
    #数据库索引
    database: 0
    host: 172.17.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: -1
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR